//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms
//6th March 2013
//Author:- Avinash Kumar Dasoundhi

//Solution:-
#include<stdio.h>
int main()
{
	int i,a=0,b=1,c,sum=0;
	for(i=1;c<4000000;i++)
	{
		c=a+b;
		a=b;
		b=c;
		if(c%2==0)
		sum=sum+c;
	}
	printf("The sum is:%d",sum);
	return 0;	
}	
